services:
  redis:
    image: redis:7.2.5
    container_name: redis-7.2.5
    restart: always
    volumes:
      - ./redis/conf:/etc/redis
      - ./redis/data:/data
      - ./redis/log:/var/log/redis
    ports:
      - "6379:6379"
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge